pipeline{
    agent any
    stages{
        stage('checkout stage'){
            steps{
                git branch:'jenkins', url: 'https://github.com/ManojKRISHNAPPA/career-devops-micro.git'
            }
        }
            stage('build'){
                steps{
                    echo "Building the webhook.sh file "
                    sh 'chmod 777 webhook.sh'
                    ./webhook.sh 
                }
            }
        }
    }
